# permissions for end users to edit rolloutdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolloutdeployment-editor-role
rules:
- apiGroups:
  - microservice.templarfelix.com
  resources:
  - rolloutdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microservice.templarfelix.com
  resources:
  - rolloutdeployments/status
  verbs:
  - get
