apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "rollout-Canary.fullname" . }}-internal-gateway
  namespace: {{ .Release.Namespace | quote }}
  annotations: {}
  labels:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    helm.sh/chart: {{ include "rollout-Canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    squad: {{ .Values.squad | required "Squad attribute is required. E.g: squad: psm-foo" }}
spec:
  selector:
    istio: internalingressgateway
  servers:
  - hosts:
    - '*.{{ .Values.domain }}'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.{{ .Values.domain }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt